# Generated by Django 4.1.2 on 2022-10-13 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('descirption', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LernKarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_front', models.CharField(max_length=180)),
                ('txt_back', models.CharField(max_length=180)),
                ('donkey_bridge', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RAM_points', models.IntegerField()),
                ('Memory_points', models.IntegerField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('lernkarte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.lernkarte')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nachricht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LernSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descirption', models.CharField(max_length=255)),
                ('languageOne', models.CharField(max_length=30)),
                ('languageTwo', models.CharField(max_length=30)),
                ('fach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.fach')),
            ],
        ),
        migrations.AddField(
            model_name='lernkarte',
            name='lernset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.lernset'),
        ),
    ]
