# Generated by Django 4.1.2 on 2022-10-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lernset',
            name='languageOne',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='lernset',
            name='languageTwo',
            field=models.CharField(max_length=2),
        ),
    ]
