# Generated by Django 4.1.2 on 2022-10-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_lernset_languageone_alter_lernset_languagetwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fach',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
