# Generated by Django 4.1.2 on 2022-10-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_fach_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fach',
            options={'ordering': ['user', 'name', 'descirption']},
        ),
        migrations.AlterModelOptions(
            name='lernset',
            options={'ordering': ['name', 'languageOne', 'languageTwo', 'descirption']},
        ),
        migrations.AlterField(
            model_name='lernkarte',
            name='donkey_bridge',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
