# Generated by Django 4.1.2 on 2022-10-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_fach_options_alter_lernset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lernkarte',
            name='donkey_bridge',
            field=models.CharField(max_length=80),
        ),
    ]
