# Generated by Django 4.1.2 on 2022-10-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_lernkarte_donkey_bridge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['datetime']},
        ),
        migrations.AddField(
            model_name='lernset',
            name='pausenzahl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lernset',
            name='richtung',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lernset',
            name='success_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fach',
            name='descirption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lernkarte',
            name='donkey_bridge',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='lernset',
            name='descirption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nachricht',
            name='message',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='progress',
            name='Memory_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progress',
            name='RAM_points',
            field=models.IntegerField(default=0),
        ),
    ]
