# Generated by Django 4.1.2 on 2022-10-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_progress_options_lernset_pausenzahl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lernkarte',
            name='success_points',
            field=models.IntegerField(default=0),
        ),
    ]
