# Generated by Django 4.1.2 on 2022-10-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_lernkarte_success_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='deineAntwort',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='richtigeAntwort',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='verklickt',
            field=models.BooleanField(default=False),
        ),
    ]
